(*
 Autogenerated by Thrift Compiler (0.8.0)

 DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING
*)

open Thrift
class notification :
object ('a)
  method get_notificationType : string option
  method grab_notificationType : string
  method set_notificationType : string -> unit
  method unset_notificationType : unit
  method reset_notificationType : unit
  method get_values : (string,string) Hashtbl.t option
  method grab_values : (string,string) Hashtbl.t
  method set_values : (string,string) Hashtbl.t -> unit
  method unset_values : unit
  method reset_values : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_notification : Protocol.t -> notification
class query :
object ('a)
  method get_relName : string option
  method grab_relName : string
  method set_relName : string -> unit
  method unset_relName : unit
  method reset_relName : unit
  method get_arguments : string list option
  method grab_arguments : string list
  method set_arguments : string list -> unit
  method unset_arguments : unit
  method reset_arguments : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_query : Protocol.t -> query
class queryReply :
object ('a)
  method get_result : (string list,bool) Hashtbl.t option
  method grab_result : (string list,bool) Hashtbl.t
  method set_result : (string list,bool) Hashtbl.t -> unit
  method unset_result : unit
  method reset_result : unit
  method get_exception_code : string option
  method grab_exception_code : string
  method set_exception_code : string -> unit
  method unset_exception_code : unit
  method reset_exception_code : unit
  method get_exception_message : string option
  method grab_exception_message : string
  method set_exception_message : string -> unit
  method unset_exception_message : unit
  method reset_exception_message : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_queryReply : Protocol.t -> queryReply
type fLValue = string

